{
 "title": "SLATE / Usage by application",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"\"}[1m])",
     "legendFormat": "App CPU usage"
    }
   ]
  },
  {
   "title": "Memory usage by application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "container_memory_cache{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "container_memory_swap{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",container=\"\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Network usage by application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])*8)",
     "legendFormat": "Pod Network Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])*8)",
     "legendFormat": "Pod Network Transmit"
    }
   ]
  },
  {
   "title": "Disk usage by application",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Disk Occupied"
    },
    {
     "expr": "max(container_fs_limit_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Disk Total Space"
    }
   ]
  }
 ]
}